version: "3"

services:
  web:
    image: "php:apache"
    depends_on:
      - mysql
    ports:
      - '8080:80'
    links:
      - mysql
    volumes: 
      - "./:/var/www/html"
  mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword